apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tokengen-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tokengen-frontend-service
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: tokengen-backend-service
            port:
              number: 8000
