name: Tokengen CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Backend Image
      run: |
        sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-backend:latest ./backend
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-backend:latest

    - name: Build and Push Frontend Image
      run: |
        sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-frontend:latest ./frontend
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-frontend:latest

    - name: Copy Kubernetes Manifests
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "k8s/*"
        target: "~/deploy/k8s/"

    - name: Deploy to MicroK8s
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          microk8s kubectl apply -f ~/deploy/k8s/backend-deployment.yaml
          microk8s kubectl apply -f ~/deploy/k8s/backend-service.yaml
          microk8s kubectl apply -f ~/deploy/k8s/frontend-deployment.yaml
          microk8s kubectl apply -f ~/deploy/k8s/frontend-service.yaml
          microk8s kubectl apply -f ~/deploy/k8s/ingress.yaml
