name: Tokengen CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tokengen-frontend:latest

      # ✅ Correctly indented Copy step
      - name: Copy K8s manifests to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./k8s"            
          target: "/home/${{ secrets.SERVER_USER }}/deploy/k8s" 

      # ✅ Correctly indented Deploy step
      - name: Deploy to MicroK8s
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Apply backend deployment
            microk8s kubectl apply -f /home/${{ secrets.SERVER_USER }}/deploy/k8s/backend-deployment.yaml

            # Apply frontend deployment
            microk8s kubectl apply -f /home/${{ secrets.SERVER_USER }}/deploy/k8s/frontend-deployment.yaml

            # Apply ingress
            microk8s kubectl apply -f /home/${{ secrets.SERVER_USER }}/deploy/k8s/ingress.yaml
